import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => { await page.goto('/') })

test('overview matches the composition and chart range is interactive', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Your visibility at a glance')
  await expect(page.locator('.metric-card')).toHaveCount(4)
  await expect(page.locator('.zebra-months')).toContainText('Apr')
  await expect(page.locator('.zebra-months')).toContainText('Sep')
  await expect(page.locator('.opportunity-list button, .opportunity-list a, .opportunity-list [tabindex]')).toHaveCount(0)
  await page.locator('.opportunity-card').first().click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const chart = page.getByRole('slider', { name: 'Inspect search appearances' })
  await chart.click()
  await expect(chart).toHaveCSS('outline-style', 'none')
  await page.keyboard.press('Tab')
  await page.keyboard.press('Shift+Tab')
  await expect(chart).toBeFocused()
  await expect(chart).toHaveCSS('outline-style', 'solid')
  await page.keyboard.press('ArrowLeft')
  await expect(chart).toHaveAttribute('aria-valuenow', '181')
  await chart.blur()
  await page.screenshot({ path: 'test-results/overview-desktop.png', fullPage: true })
  await page.getByRole('combobox', { name: 'Chart time range' }).click()
  await page.getByRole('option', { name: 'Last 3 months' }).click()
  await expect(page.locator('.zebra-months')).not.toContainText('Apr')
  await expect(page.locator('.zebra-months')).toContainText('Jul')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('adding queries validates duplicates and persists across reloads', async ({ page }) => {
  await page.getByRole('button', { name: 'Add queries', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Search queries', { exact: true }).fill('Best tools for a remote startup\nBest tools for a remote startup\nProduct planning for founders')
  await dialog.getByRole('button', { name: 'Add queries', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.locator('[data-sonner-toast]')).toContainText('2 queries saved')
  await page.getByRole('link', { name: 'Settings', exact: true }).click()
  await expect(page.locator('.settings-list')).toContainText(['', '130 / 200'])
  await page.reload()
  await expect(page.locator('.settings-list')).toContainText(['', '130 / 200'])
  await page.getByRole('link', { name: 'Overview', exact: true }).click()
  await page.getByRole('button', { name: 'Add queries', exact: true }).first().click()
  await dialog.getByLabel('Search queries', { exact: true }).fill('product planning for founders')
  await dialog.getByRole('button', { name: 'Add queries', exact: true }).click()
  await expect(dialog.getByRole('alert')).toHaveText('These queries are already tracked.')
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
})

test('opportunities show recommendations inside a locked preview', async ({ page }) => {
  await page.getByRole('link', { name: 'Opportunities', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Coming soon', exact: true })).toBeVisible()
  await expect(page.locator('.coming-soon-preview')).toHaveAttribute('inert', '')
  await expect(page.locator('.opportunities-recommendation').first()).toContainText('Recommended action')
  await expect(page.locator('.opportunities-ranking li')).toHaveCount(8)
  await expect(page.getByRole('button', { name: 'Review opportunity' })).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Coming soon', exact: true })).toBeVisible()
})

test('appearance opens its existing content from navigation and direct links', async ({ page }) => {
  await page.getByRole('link', { name: 'Performance', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Search performance', level: 2, exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Appearance by model', exact: true })).toBeVisible()
  await expect(page.getByRole('searchbox', { name: 'Search tracked queries' })).toBeVisible()
  await expect(page.locator('.coming-soon-stage')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('searchbox', { name: 'Search tracked queries' })).toBeVisible()
})

test('unfinished pages are locked previews, including direct links', async ({ page }) => {
  for (const name of ['Search activity', 'Opportunities', 'Competitors', 'Reports']) {
    await page.goto(`/#${encodeURIComponent(name)}`)
    await expect(page.getByRole('heading', { name: 'Coming soon', exact: true })).toBeVisible()
    await expect(page.locator('.coming-soon-preview')).toHaveAttribute('inert', '')
    await expect(page.locator('.coming-soon-preview')).toHaveAttribute('aria-hidden', 'true')
    await expect(page.getByRole('button', { name: 'Add queries', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Back to Overview' }).click()
    await expect(page.getByRole('heading', { level: 1 })).toHaveText('Your visibility at a glance')
  }
})

test('overview reporting period still changes metrics', async ({ page }) => {
  await page.getByRole('combobox', { name: 'Reporting period' }).click()
  await page.getByRole('option', { name: 'Last 7 days' }).click()
  await expect(page.locator('.metric-card').nth(1)).toContainText('768')
})

test('mobile dashboard fits and navigation remains usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  await expect(page.locator('.zebra-months')).toContainText('Sep')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/overview-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('link', { name: 'Competitors', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('The competitive landscape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await expect(page.getByRole('heading', { name: 'Coming soon', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Back to Overview' }).click()
  await page.getByRole('button', { name: 'Add queries', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
})


test('sidebar stays compact while dashboard content scrolls', async ({ page }) => {
  await page.setViewportSize({ width: 1470, height: 740 })
  const sidebar = page.getByRole('complementary', { name: 'Main navigation' })
  await expect(sidebar.getByRole('button', { name: 'Jordan Lee' })).toBeVisible()
  const dimensions = await sidebar.evaluate(element => ({ height: element.clientHeight, content: element.scrollHeight }))
  expect(dimensions.content).toBeLessThanOrEqual(dimensions.height)
  await sidebar.hover()
  await page.mouse.wheel(0, 600)
  expect(await sidebar.evaluate(element => element.scrollTop)).toBe(0)
  await page.locator('main').hover()
  await page.mouse.wheel(0, 600)
  await expect.poll(() => page.locator('main').evaluate(element => element.scrollTop)).toBeGreaterThan(0)
  expect(await page.evaluate(() => window.scrollY)).toBe(0)
  await page.getByRole('button', { name: 'Collapse sidebar' }).click()
  await expect(page.getByRole('button', { name: 'Expand sidebar' })).toBeVisible()
  await page.getByRole('link', { name: 'Performance', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Search performance')
})

test('dialog traps focus, restores it, and validates search model selection', async ({ page }) => {
  const trigger = page.getByRole('button', { name: 'Add queries', exact: true })
  await trigger.click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Search queries', { exact: true }).fill('A new startup query')
  await dialog.getByRole('checkbox', { name: 'All Models', exact: true }).uncheck()
  await dialog.getByRole('button', { name: 'Add queries', exact: true }).click()
  await expect(dialog.getByRole('alert')).toHaveText('Select at least one search model.')
  await page.keyboard.press('Tab')
  expect(await dialog.evaluate(element => element.contains(document.activeElement))).toBe(true)
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(trigger).toBeFocused()
})

test('appearance query selection synchronizes the chart and models', async ({ page }) => {
  await page.goto('/#Performance')
  const search = page.getByRole('searchbox', { name: 'Search tracked queries' })
  await search.fill('startups')
  await page.locator('.query-results button').filter({ hasText: 'Best project management tool for startups' }).click()
  await expect(search).toHaveAttribute('placeholder', 'Best project management tool for startups')
  await expect(page.getByRole('meter', { name: 'Gemini appearance rate' })).not.toHaveAttribute('aria-valuetext', 'No data')
  await expect(page.locator('.competing-row.is-selected')).toContainText('Best project management tool for startups')
  await page.getByRole('combobox', { name: 'Reporting period' }).click()
  await page.getByRole('option', { name: 'Last 7 days', exact: true }).click()
  await expect(page.locator('.chart-summary')).toContainText('Last 7 days')
  await page.locator('.competing-row').filter({ hasText: 'Linear alternatives' }).click()
  await expect(page.getByRole('meter', { name: 'Gemini appearance rate' })).not.toHaveAttribute('aria-valuetext', 'No data')
  await page.getByRole('button', { name: 'Clear query selection' }).click()
  await expect(page.locator('.zebra-chart')).toBeVisible()
  await expect(page.locator('.chart-summary')).toContainText('2,846')
  await search.fill('unmatched search')
  await expect(page.locator('.query-results')).toContainText('No matching queries')
  await page.keyboard.press('Escape')
  await expect(page.locator('.query-results')).not.toBeVisible()
  await page.setViewportSize({width:390,height:844})
  await expect(page.getByRole('heading', { name: 'Competing Queries', exact: true })).toBeAttached()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('appearance saved queries have an honest no-data state', async ({ page }) => {
  await page.evaluate(() => localStorage.setItem('lava-queries-v1', JSON.stringify([{id:'new-demo-query', text:'A newly tracked query', models:['ChatGPT'], rate:null}])))
  await page.goto('/#Performance')
  await page.reload()
  await page.getByRole('searchbox', { name:'Search tracked queries' }).fill('newly tracked')
  await page.locator('.query-results button').filter({hasText:'A newly tracked query'}).click()
  await expect(page.locator('.zebra-empty')).toContainText('No results yet')
  await expect(page.getByRole('meter', {name:'ChatGPT appearance rate'})).toHaveAttribute('aria-valuetext','No data')
})

test('appearance chart keeps its layout and styling across query selections', async ({ page }) => {
  await page.setViewportSize({ width: 1470, height: 920 })
  await page.goto('/#Performance')
  await page.evaluate(() => document.fonts.ready)
  const panel = page.locator('.chart-panel')
  const chart = page.locator('.zebra-chart')
  const originalPanel = await panel.boundingBox()
  const originalChart = await chart.boundingBox()
  for (const name of ['Best AI visibility tools', 'Email marketing tools']) {
    await page.getByRole('button', { name, exact: true }).click()
    expect(await panel.boundingBox()).toEqual(originalPanel)
    expect(await chart.boundingBox()).toEqual(originalChart)
    await expect(page.getByRole('combobox', { name: 'Chart time range' })).toContainText('Last 6 months')
    await expect(page.locator('.chart-summary strong')).toHaveText(/%$/)
    await expect(page.locator('.zebra-latest')).toHaveText(/%$/)
    await expect(page.locator('.zebra-art pattern')).toHaveCount(1)
    await expect(page.locator('.zebra-art path[fill="none"]')).toHaveCount(2)
    await expect(page.locator('.zebra-art path[fill="none"]').first()).toHaveAttribute('stroke', '#6571ef')
    await expect(page.locator('.zebra-legend')).toContainText(name === 'Email marketing tools' ? 'Sigma Eta Pi' : 'SparkSC')
    await page.getByRole('slider', { name: 'Inspect search appearances' }).focus()
    await page.keyboard.press('Home')
    await expect(page.locator('.zebra-interaction circle')).toHaveCount(2)
    await expect(page.locator('.zebra-interaction')).toHaveAttribute('aria-valuetext', /Apr 1.*(SparkSC|Sigma Eta Pi)/)
    await page.keyboard.press('Escape')
    await expect(page.locator('.zebra-interaction')).toContainText('100%')
  }
  await page.getByRole('button', { name: 'All queries', exact: true }).click()
  expect(await panel.boundingBox()).toEqual(originalPanel)
  expect(await chart.boundingBox()).toEqual(originalChart)
  await expect(page.locator('.chart-summary strong')).toHaveText('2,846')
})

test('appearance prompt mosaic fits three rows and synchronizes selection', async ({ page }) => {
  await page.setViewportSize({ width: 1470, height: 920 })
  await page.goto('/#Performance')
  const pills = page.getByRole('group', { name: 'Query shortcuts' })
  await expect(pills.getByRole('button')).toHaveCount(11)
  await page.evaluate(() => document.fonts.ready)
  expect(await pills.locator('button').evaluateAll(nodes => new Set(nodes.map(n => n.offsetTop)).size)).toBe(3)
  await expect(pills.getByRole('button').first()).toHaveText('All queries')
  expect(await pills.locator('button').evaluateAll(nodes => nodes.slice(1).map(n => n.classList.contains('is-high') ? 'high' : 'low'))).toEqual([...Array(5).fill('high'), ...Array(5).fill('low')])
  await pills.getByRole('button', { name: 'Best AI visibility tools', exact: true }).click()
  await expect(page.getByRole('searchbox', { name: 'Search tracked queries' })).toHaveAttribute('placeholder', 'Best AI visibility tools')
  await expect(page.getByRole('meter')).toHaveCount(10)
  await pills.getByRole('button', { name: 'All queries', exact: true }).click()
  await expect(page.locator('.zebra-chart')).toBeVisible()
  await page.getByRole('button', { name: 'Reorder models', exact: true }).click()
  await page.getByRole('button', { name: 'Move Perplexity up', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.locator('.full-height-models .model-name').first()).toHaveText('Perplexity')
  await expect.poll(() => page.locator('.full-height-models img').evaluateAll(images => images.every(img => img instanceof HTMLImageElement && img.complete && img.naturalWidth > 0))).toBe(true)
  await page.screenshot({ path: 'test-results/appearance-desktop.png', fullPage: true })
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('model panel scroll stays contained with readable endpoints', async ({ page }) => {
  await page.setViewportSize({ width: 1470, height: 640 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/#Performance')
  const panel = page.locator('.full-height-models')
  const list = panel.locator('.model-list')
  await expect(list).toHaveAttribute('data-overflowing', 'true')
  await expect(panel.locator('.is-top')).toHaveCSS('opacity', '0')
  await expect(panel.locator('.is-bottom')).toHaveCSS('opacity', '1')
  await page.locator('main').evaluate(e => { e.scrollTop = 180 })
  const pageScroll = await page.locator('main').evaluate(e => e.scrollTop)
  await list.hover()
  await page.mouse.wheel(0, 600)
  await expect.poll(() => list.evaluate(e => e.scrollTop)).toBeGreaterThan(0)
  await expect(panel.locator('.is-bottom')).toHaveCSS('opacity', '0')
  await expect(panel.locator('.is-top')).toHaveCSS('opacity', '1')
  await page.mouse.wheel(0, 600)
  expect(await page.locator('main').evaluate(e => e.scrollTop)).toBe(pageScroll)
  await expect(panel.getByRole('button', { name: 'Reorder models', exact: true })).toBeInViewport()
  await panel.locator('.model-row').first().focus()
  await expect.poll(() => list.evaluate(e => e.scrollTop)).toBe(0)
  await page.setViewportSize({ width: 1470, height: 1000 })
  await expect(list).toHaveAttribute('data-overflowing', 'false')
  await expect(panel.locator('.is-bottom')).toHaveCSS('opacity', '0')
})

test('demo query colors agree with overall model trends in every reporting period', async ({ page }) => {
  await page.goto('/#Performance')
  for (const days of [7, 28, 90]) {
    await page.getByRole('combobox', { name: 'Reporting period' }).click()
    await page.getByRole('option', { name: `Last ${days} days`, exact: true }).click()
    for (const tier of ['high', 'low']) {
      const pills = page.locator(`.appearance-query-pill.is-${tier}`)
      for (let i = 0; i < await pills.count(); i++) {
        await pills.nth(i).click()
        const deltas = await page.locator('.full-height-models .model-delta').evaluateAll(nodes => nodes.map(n => n.getAttribute('aria-label')).filter(label => label !== 'No data'))
        const agreeing = deltas.filter(label => label?.startsWith(tier === 'high' ? 'Increased' : 'Decreased'))
        expect(agreeing.length).toBeGreaterThan(deltas.length / 2)
        await expect(page.locator('.chart-summary .badge')).toContainText(tier === 'high' ? '+' : '-')
      }
    }
  }
})

test('query search replaces chips above the input without moving the chart', async ({ page }) => {
  await page.goto('/#Performance')
  const search = page.getByRole('searchbox', { name: 'Search tracked queries' })
  const chart = page.locator('.zebra-chart')
  const initialChart = await chart.boundingBox()
  const initialInput = await page.locator('.query-picker').boundingBox()
  const slot = await page.locator('.query-shortcuts-slot').boundingBox()
  await search.click()
  const results = page.getByRole('listbox', { name: 'Matching queries' })
  await expect.poll(() => results.boundingBox()).toEqual({ ...slot, y: slot!.y - 48, height: slot!.height + 48 })
  await expect(page.getByRole('heading', { name: 'Search performance', level: 2, exact: true })).not.toBeVisible()
  expect(await chart.boundingBox()).toEqual(initialChart)
  expect(await page.locator('.query-picker').boundingBox()).toEqual(initialInput)
  await expect(page.getByRole('group', { name: 'Query shortcuts' })).not.toBeVisible()
  await search.fill('AI visibility')
  await search.press('ArrowDown')
  await search.press('ArrowDown')
  await search.press('Enter')
  await expect(results).not.toBeVisible()
  await expect(search).toBeFocused()
  await expect(search).toHaveAttribute('placeholder', 'Best AI visibility tools')
  await search.click()
  await search.press('Escape')
  await expect(results).not.toBeVisible()
  await expect(page.getByRole('group', { name: 'Query shortcuts' })).toBeVisible()
  await search.click()
  await page.locator('.chart-summary strong').click()
  await expect(results).not.toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await search.click()
  const mobileResults = await results.boundingBox()
  const mobileInput = await search.boundingBox()
  expect(mobileResults!.y + mobileResults!.height).toBeLessThan(mobileInput!.y)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('every seeded demo query has complete model metrics and competitor data', async ({ page }) => {
  await page.goto('/#Performance')
  await expect(page.locator('.competing-query strong')).toHaveCount(15)
  const names = await page.locator('.competing-query strong').allTextContents()
  expect(names.length).toBe(15)
  const competitors = await page.locator('.competing-competitor').allTextContents()
  expect(competitors.every(name => name.trim() && name.trim() !== '—')).toBe(true)
  await expect.poll(() => page.locator('.competing-competitor img').evaluateAll(images => images.every(img => img instanceof HTMLImageElement && img.complete && img.naturalWidth > 0))).toBe(true)
  const search = page.getByRole('searchbox', { name: 'Search tracked queries' })
  for (const name of names) {
    await search.fill(name)
    await page.locator('.query-results button').filter({ hasText: name }).click()
    const metrics = await page.getByRole('meter').evaluateAll(nodes => nodes.map(n => n.getAttribute('aria-valuenow')))
    expect(metrics).toHaveLength(10)
    expect(metrics.every(value => value !== null && Number(value) >= 0 && Number(value) <= 100)).toBe(true)
    await expect(page.locator('.full-height-models .model-delta[aria-label="No data"]')).toHaveCount(0)
  }
})


test('comparison shares total less than 100 percent throughout every query history', async ({ page }) => {
  await page.goto('/#Performance')
  const shortcuts = page.getByRole('group', { name: 'Query shortcuts' }).getByRole('button')
  await expect(shortcuts).toHaveCount(11)
  for (let index = 1; index < await shortcuts.count(); index++) {
    await shortcuts.nth(index).click()
    const lines = page.locator('.zebra-art path[fill="none"]')
    await expect(lines).toHaveCount(2)
    const histories = await lines.evaluateAll(paths => paths.map(path =>
      [...path.getAttribute('d')!.matchAll(/[ML]([\d.]+),([\d.]+)/g)].map(point => (144 - Number(point[2])) / 122 * 100)
    ))
    expect(histories[0]).toHaveLength(183)
    expect(histories[1]).toHaveLength(183)
    for (let day = 0; day < 183; day++) {
      expect(histories[0][day]).toBeGreaterThanOrEqual(0)
      expect(histories[1][day]).toBeGreaterThanOrEqual(0)
      expect(histories[0][day] + histories[1][day]).toBeLessThan(100)
    }
  }
})
